[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "IdentifyingOpticalNonclassicality"
version = "0.0.1"
description = "A variational model that learns a nonclassicality indicator"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "equinox==0.13.1",
    "exqalibur==1.0.0",
    "numpy",
    "scipy",
    "jax==0.7.2",
    "jaxtyping==0.3.3",
    "latexcodec==3.0.1",
    "pytorch",
    "tabulate",
    "perceval-quandela",
    "pytest",
    "pytest-cov"
]
